### ISSUE TITLE
Nuget 3.5 deploy fails with 'Ambiguous option'

### ISSUE THREAD

**Issue by AlyceBills** [Xyanid/NuGetDeploy#3]
I updated my NuGet version to 3.5 (both the Visual Studio Package Manager and nuget.exe), and since then, deployment fails with the following error.
> An Error occured while deploying the nuPkg file: Ambiguous option 's'. Possible values: Source SymbolSource SymbolApiKey.

I see that [these guys](https://github.com/fsharp/FAKE/issues/1415) had the same issue - the push command being called with '-s'. They fixed it by using the full name of the switch (-source).

**Comment by Xyanid** [comment]
Thanks for the fix, I will prepare a new release for it
